-- --------------------------------------------------------
-- 主机:                           127.0.0.1
-- 服务器版本:                        10.3.7-MariaDB - mariadb.org binary distribution
-- 服务器OS:                        Win64
-- HeidiSQL 版本:                  10.1.0.5577
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table kf_inoma_weiwei_agv.control_pi_info
DROP TABLE IF EXISTS `control_pi_info`;
CREATE TABLE IF NOT EXISTS `control_pi_info` (
  `type` varchar(60) NOT NULL COMMENT '类型',
  `key` varchar(60) NOT NULL DEFAULT '1' COMMENT '变量名称',
  `value` int(11) DEFAULT NULL COMMENT '当前状态',
  `explan` varchar(100) DEFAULT '' COMMENT '字段解释',
  PRIMARY KEY (`type`,`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='交通管制控制基础参数表';

-- Dumping data for table kf_inoma_weiwei_agv.control_pi_info: ~37 rows (大约)
DELETE FROM `control_pi_info`;
/*!40000 ALTER TABLE `control_pi_info` DISABLE KEYS */;
INSERT INTO `control_pi_info` (`type`, `key`, `value`, `explan`) VALUES
	('BASIC_INFO', 'ANGLE_ALLOWED_DEVIATION', 20, ''),
	('BASIC_INFO', 'DISTANCE_IN_LINE_DANGEROUS', 2500, '小于此按照在一条线上计算'),
	('BASIC_INFO', 'DISTANCE_IN_LINE_SAFE', 3000, '大于此为可完全平行距离'),
	('BASIC_INFO', 'DISTANCE_XY_REPEAT_POINT', 100, '记录运行轨迹时，两个点的距离在此之内时算作重复点，不做重复记录'),
	('OTHERS_1_POSITIVE_CLOSE_1_OTHERS', 'DISTANCE_DANGEROUS', 8000, ''),
	('OTHERS_1_POSITIVE_CLOSE_1_OTHERS', 'DISTANCE_DANGEROUS_OTHERS', 4000, ''),
	('OTHERS_1_POSITIVE_CLOSE_1_OTHERS', 'DISTANCE_SAFE', 10000, ''),
	('OTHERS_1_POSITIVE_CLOSE_1_OTHERS', 'DISTANCE_WARNING', 9000, ''),
	('OTHERS_1_POSITIVE_FARAWAY_1_OTHERS', 'DISTANCE_DANGEROUS', 6000, ''),
	('OTHERS_1_POSITIVE_FARAWAY_1_OTHERS', 'DISTANCE_DANGEROUS_OTHERS', 4000, ''),
	('OTHERS_1_POSITIVE_FARAWAY_1_OTHERS', 'DISTANCE_SAFE', 8000, ''),
	('OTHERS_1_POSITIVE_FARAWAY_1_OTHERS', 'DISTANCE_WARNING', 7000, ''),
	('OTHERS_2_OTHERS', 'DISTANCE_DANGEROUS', 5000, ''),
	('OTHERS_2_OTHERS', 'DISTANCE_DANGEROUS_ONE', 9000, ''),
	('OTHERS_2_OTHERS', 'DISTANCE_SAFE', 12000, ''),
	('OTHERS_2_OTHERS', 'DISTANCE_WARNING', 10000, ''),
	('PARALLEL_CONVERSE_IN_LINE', 'DISTANCE_DANGEROUS', 16000, ''),
	('PARALLEL_CONVERSE_IN_LINE', 'DISTANCE_SAFE', 20000, ''),
	('PARALLEL_CONVERSE_IN_LINE', 'DISTANCE_WARNING', 18000, ''),
	('PARALLEL_CONVERSE_IN_PARALLEL', 'DISTANCE_DANGEROUS', 0, ''),
	('PARALLEL_CONVERSE_IN_PARALLEL', 'DISTANCE_SAFE', 7000, ''),
	('PARALLEL_CONVERSE_IN_PARALLEL', 'DISTANCE_WARNING', 4000, ''),
	('PARALLEL_SYNTROPY_IN_LINE', 'DISTANCE_DANGEROUS', 6500, ''),
	('PARALLEL_SYNTROPY_IN_LINE', 'DISTANCE_SAFE', 8000, ''),
	('PARALLEL_SYNTROPY_IN_LINE', 'DISTANCE_WARNING', 7500, ''),
	('PARALLEL_SYNTROPY_IN_PARALLEL', 'DISTANCE_DANGEROUS', 7000, ''),
	('PARALLEL_SYNTROPY_IN_PARALLEL', 'DISTANCE_SAFE', 8000, ''),
	('PARALLEL_SYNTROPY_IN_PARALLEL', 'DISTANCE_WARNING', 6000, ''),
	('VERTICAL_1_CLOSE_1_FARAWAY', 'DISTANCE_DANGEROUS_CLOSE', 6000, ''),
	('VERTICAL_1_CLOSE_1_FARAWAY', 'DISTANCE_DANGEROUS_FARAWAY', 8000, ''),
	('VERTICAL_1_CLOSE_1_FARAWAY', 'DISTANCE_WARNING', 7000, ''),
	('VERTICAL_2_CLOSE', 'DISTANCE_DANGEROUS', 7000, ''),
	('VERTICAL_2_CLOSE', 'DISTANCE_SAFE', 14000, ''),
	('VERTICAL_2_CLOSE', 'DISTANCE_WARNING', 12000, ''),
	('VERTICAL_2_FARAWAY', 'DISTANCE_DANGEROUS', 4000, ''),
	('VERTICAL_2_FARAWAY', 'DISTANCE_SAFE', 10000, ''),
	('VERTICAL_2_FARAWAY', 'DISTANCE_WARNING', 6000, '');
/*!40000 ALTER TABLE `control_pi_info` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
